### ISSUE TITLE
vae demo: AttributeError: module 'flax.linen' has no attribute 'apply'

### ISSUE THREAD

**Issue by brettkoonce** [google/flax#1122]
> python3 train.py 2>&1 | tee -a error.log

produces

```
I0312 19:35:51.672157 139827102652224 dataset_info.py:354] Load dataset info from /home/skoonce/tensorflow_datasets/binarized_mnist/1.0.0
I0312 19:35:51.673851 139827102652224 dataset_builder.py:354] Reusing dataset binarized_mnist (/home/skoonce/tensorflow_datasets/binarized_mnist/1.0.0)
I0312 19:35:51.673945 139827102652224 dataset_builder.py:570] Constructing tf.data.Dataset for split train, from /home/skoonce/tensorflow_datasets/binarized_mnist/1.0.0
I0312 19:35:51.738107 139827102652224 dataset_builder.py:570] Constructing tf.data.Dataset for split test, from /home/skoonce/tensorflow_datasets/binarized_mnist/1.0.0
Traceback (most recent call last):
  File "train.py", line 217, in <module>
    app.run(main)
  File "/home/skoonce/.local/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/skoonce/.local/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "train.py", line 206, in main
    metrics, comparison, sample = eval(optimizer.target, test_ds, z, eval_rng)
  File "/home/skoonce/.local/lib/python3.6/site-packages/jax/api.py", line 416, in f_jitted
    return cpp_jitted_f(context, *args, **kwargs)
  File "/home/skoonce/.local/lib/python3.6/site-packages/jax/api.py", line 303, in cache_miss
    donated_invars=donated_invars)
  File "/home/skoonce/.local/lib/python3.6/site-packages/jax/core.py", line 1394, in bind
    return call_bind(self, fun, *args, **params)
  File "/home/skoonce/.local/lib/python3.6/site-packages/jax/core.py", line 1385, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/home/skoonce/.local/lib/python3.6/site-packages/jax/core.py", line 1397, in process
    return trace.process_call(self, fun, tracers, params)
  File "/home/skoonce/.local/lib/python3.6/site-packages/jax/core.py", line 625, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/home/skoonce/.local/lib/python3.6/site-packages/jax/interpreters/xla.py", line 587, in _xla_call_impl
    *unsafe_map(arg_spec, args))
  File "/home/skoonce/.local/lib/python3.6/site-packages/jax/linear_util.py", line 260, in memoized_fun
    ans = call(fun, *args)
  File "/home/skoonce/.local/lib/python3.6/site-packages/jax/interpreters/xla.py", line 662, in _xla_callable
    jaxpr, out_avals, consts = pe.trace_to_jaxpr_final(fun, abstract_args)
  File "/home/skoonce/.local/lib/python3.6/site-packages/jax/interpreters/partial_eval.py", line 1220, in trace_to_jaxpr_final
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(fun, main, in_avals)
  File "/home/skoonce/.local/lib/python3.6/site-packages/jax/interpreters/partial_eval.py", line 1200, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers)
  File "/home/skoonce/.local/lib/python3.6/site-packages/jax/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "train.py", line 156, in eval
    return nn.apply(eval_model, model())({'params': params})
AttributeError: module 'flax.linen' has no attribute 'apply'
```
walking back 05aab84e0650f006b45b4bff0262ca9d26ca088f, eg

    git reset --hard 917f447057c93aa0e10708743d7a7d913255a6ad

works again:

```
eval epoch: 25, loss: 101.4085, BCE: 73.8702, KLD: 27.5383
eval epoch: 26, loss: 101.2129, BCE: 73.8819, KLD: 27.3310
eval epoch: 27, loss: 101.2679, BCE: 73.3930, KLD: 27.8748
eval epoch: 28, loss: 101.1449, BCE: 73.5432, KLD: 27.6017
eval epoch: 29, loss: 100.9072, BCE: 73.1581, KLD: 27.7491
eval epoch: 30, loss: 101.2102, BCE: 73.0929, KLD: 28.1173
```

**Comment by jheek** [comment]
You probably forked the example from master and installed flax via pip install.
We directly merge into master so the examples you see on this branch might use features that are not yet released on pip.

**Comment by brettkoonce** [comment]
fair enough, after reinstalling from master, eg

    pip install --upgrade git+https://github.com/google/flax.git 

things work.  thought I had upgraded, sorry!

```
Successfully built flax
Installing collected packages: flax
  Attempting uninstall: flax
    Found existing installation: flax 0.3.0
    Uninstalling flax-0.3.0:
      Successfully uninstalled flax-0.3.0
Successfully installed flax-0.3.2
```

**Comment by yukiweng62** [comment]
I received an similar error from flax 0.7.5, could u help me:

File ~\AppData\Roaming\Python\Python311\site-packages\jVMC\nets_init_.py:5 from jVMC.nets.rnn import *
File ~\AppData\Roaming\Python\Python311\site-packages\jVMC\nets\rnn.py:92 class RNN(nn.Module):
File ~\AppData\Roaming\Python\Python311\site-packages\jVMC\nets\rnn.py:138 in RNN @partial(nn.transforms.scan,
AttributeError: module 'flax.linen' has no attribute 'transforms'

I have tried flax 0.7.4 after I solved an AttributeError: module 'flax' has no attribute 'nn'
Many thanks!!!
