### ISSUE TITLE
ogbg_molpcba example doesn't run on multi GPU machine

### ISSUE THREAD

**Issue by ckt624** [google/flax#1620]
When I try to run ogbg_molpcba example on a multi GPU machine by default config:
 
python main.py --workdir=./ogbg_molpcba --config=configs/default.py

I get error 

Traceback (most recent call last):
  File "main.py", line 65, in <module>
    app.run(main)
  File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "main.py", line 60, in main
    train.train_and_evaluate(FLAGS.config, FLAGS.workdir)
  File "/home/kongtao/flax/examples/ogbg_molpcba/train.py", line 352, in train_and_evaluate
    state, graphs, rngs={'dropout': dropout_rng})
  File "/home/kongtao/flax/examples/ogbg_molpcba/train.py", line 223, in train_step
    loss=loss, logits=logits, labels=labels, mask=mask)
  File "/opt/conda/lib/python3.7/site-packages/clu/metrics.py", line 366, in single_from_model_output
    return cls._from_model_output(**kwargs)
  File "/opt/conda/lib/python3.7/site-packages/clu/metrics.py", line 350, in _from_model_output
    for metric_name, metric in cls.__annotations__.items()
  File "/opt/conda/lib/python3.7/site-packages/clu/metrics.py", line 350, in <dictcomp>
    for metric_name, metric in cls.__annotations__.items()
  File "/opt/conda/lib/python3.7/site-packages/clu/metrics.py", line 182, in from_model_output
    return super().from_model_output(output, mask=mask)
  File "/opt/conda/lib/python3.7/site-packages/clu/metrics.py", line 461, in from_model_output
    utils.check_param(values, ndim=1)
  File "/opt/conda/lib/python3.7/site-packages/clu/internal/utils.py", line 71, in check_param
    raise ValueError(f"Expected ndim={ndim}, got ndim={value.ndim}")
ValueError: Expected ndim=1, got ndim=2
2021-10-15 20:17:10.136691: W tensorflow/core/kernels/data/generator_dataset_op.cc:107] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.

This error remains when I only use 1 GPU and run

CUDA_VISIBLE_DEVICES=0 python main.py --workdir=./ogbg_molpcba --config=configs/default.py

If I remove the clu metrics codes that causes this error, the code fails on the model functions:

Traceback (most recent call last):
  File "main.py", line 65, in <module>
    app.run(main)
  File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "main.py", line 60, in main
    train.train_and_evaluate(FLAGS.config, FLAGS.workdir)
  File "/home/kongtao/flax/examples/ogbg_molpcba/train.py", line 352, in train_and_evaluate
    state, graphs, rngs={'dropout': dropout_rng})
  File "/home/kongtao/flax/examples/ogbg_molpcba/train.py", line 223, in train_step
    loss=loss, logits=logits, labels=labels, mask=mask)
  File "/opt/conda/lib/python3.7/site-packages/clu/metrics.py", line 366, in single_from_model_output
    return cls._from_model_output(**kwargs)
  File "/opt/conda/lib/python3.7/site-packages/clu/metrics.py", line 350, in _from_model_output
    for metric_name, metric in cls.__annotations__.items()
  File "/opt/conda/lib/python3.7/site-packages/clu/metrics.py", line 350, in <dictcomp>
    for metric_name, metric in cls.__annotations__.items()
  File "/opt/conda/lib/python3.7/site-packages/clu/metrics.py", line 182, in from_model_output
    return super().from_model_output(output, mask=mask)
  File "/opt/conda/lib/python3.7/site-packages/clu/metrics.py", line 461, in from_model_output
    utils.check_param(values, ndim=1)
  File "/opt/conda/lib/python3.7/site-packages/clu/internal/utils.py", line 71, in check_param
    raise ValueError(f"Expected ndim={ndim}, got ndim={value.ndim}")
ValueError: Expected ndim=1, got ndim=2
2021-10-15 20:17:10.136691: W tensorflow/core/kernels/data/generator_dataset_op.cc:107] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.

How can we fix this?

**Comment by jheek** [comment]
I don't think this is related to the GPUs. Did you install the requirements.txt in the example dir? From the stack trace it looks like you are running with an outdated version of clu?

**Comment by jheek** [comment]
Closing due to lack of activity
