### ISSUE TITLE
Fail to execute regression tests

### ISSUE THREAD

**Issue by mattiasmar** [google/flax#1823]
### Problem you have encountered:
Following the instructions of https://flax.readthedocs.io/en/latest/contributing.html at the step ./tests/run_all_tests.sh the error `jinja2.exceptions.TemplateNotFound: flax_module` is encountered.

### What you expected to happen:
Tests to execute from A to Z.

### Logs, error messages, etc:
```
Exception occurred:
  File "/usr/lib/python3/dist-packages/sphinx/jinja2glue.py", line 233, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: flax_module
The full traceback has been saved in /tmp/sphinx-err-j5q3iduz.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
error code 2
root@jax2-set-1:~/flax# cat /tmp/sphinx-err-j5q3iduz.log
# Sphinx version: 1.8.5
# Python version: 3.8.10 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 3.0.3
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/cmd/build.py", line 300, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 263, in __init__
    self._init_builder()
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 325, in _init_builder
    self.emit('builder-inited')
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 510, in emit
    return self.events.emit(event, self, *args)
  File "/usr/lib/python3/dist-packages/sphinx/events.py", line 80, in emit
    results.append(callback(*args))
  File "/usr/lib/python3/dist-packages/sphinx/ext/autosummary/__init__.py", line 693, in process_generate_options
    generate_autosummary_docs(genfiles, builder=app.builder,
  File "/usr/lib/python3/dist-packages/sphinx/ext/autosummary/generate.py", line 170, in generate_autosummary_docs
    template = template_env.get_template(template_name)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/usr/local/lib/python3.8/dist-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/lib/python3/dist-packages/sphinx/jinja2glue.py", line 233, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: flax_module
```

### Steps to reproduce:
Follow the instructions of https://flax.readthedocs.io/en/latest/contributing.html but with Python version 3.8.10 in an ubuntu 20 docker image (`nvidia/cuda:11.4.2-cudnn8-devel-ubuntu20.04`)

**Comment by jheek** [comment]
@marcvanzee is this related to the recent doc build failure?

**Comment by marcvanzee** [comment]
@jheek could be, but I don't think so. The error seems to be about `flax_module`, which is a custom ReadTheDocs directive for displaying the Flax Modules correctly. It lives here: https://github.com/google/flax/blob/main/docs/_templates/autosummary/flax_module.rst

I don't understand this error actually, I just tried running `run_all_tests.sh` locally and I don't get the error. @mattiasmar could you try rebasing to our master branch and try again? If the problem still appears, could you check if the file `docs/_templates/autosummary/flax_module.rst` exists in your local client?

**Comment by marcvanzee** [comment]
@mattiasmar any updates on this?

**Comment by mattiasmar** [comment]
I can get to this in maybe a month from now. If the problem still exists then, we could re-open the issue. Thanks.
