### ISSUE TITLE
UNKNOWN error when calling Conv

### ISSUE THREAD

**Issue by wilson1yan** [google/flax#2047]
### System information
- TPU v3-8
- Ubuntu 20.04.3
- `jax==0.3.6`
- `jaxlib==0.3.6`
- `libtpu-nightly==0.1.dev20220412`
- `flax==0.4.1`

### Problem you have encountered:
When I run the following script:
```
import numpy as np
import jax
import flax.linen as nn

x = np.random.randn(1, 256, 256, 3)
conv = nn.Conv(128, [3, 3], padding=[1, 1])
out = conv.init({'params': jax.random.PRNGKey(0)}, x)
print('Passed')
```
It produces the following error. This issue is not unique to the jax version (has occurred for me for `0.3.4` and `0.3.5`), and has also occurred for me on GPUs.

```
Traceback (most recent call last):
  File "test_flax.py", line 8, in <module>
    out = conv.init({'params': jax.random.PRNGKey(0)}, x)
  File "/home/wilson/.local/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/wilson/.local/lib/python3.8/site-packages/flax/linen/module.py", line 1230, in init
    _, v_out = self.init_with_output(
  File "/home/wilson/.local/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/wilson/.local/lib/python3.8/site-packages/flax/linen/module.py", line 1197, in init_with_output
    return self.apply(
  File "/home/wilson/.local/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/wilson/.local/lib/python3.8/site-packages/flax/linen/module.py", line 1162, in apply
    return apply(
  File "/home/wilson/.local/lib/python3.8/site-packages/flax/core/scope.py", line 806, in wrapper
    y = fn(root, *args, **kwargs)
  File "/home/wilson/.local/lib/python3.8/site-packages/flax/linen/module.py", line 1446, in scope_fn
    return fn(module.clone(parent=scope), *args, **kwargs)
  File "/home/wilson/.local/lib/python3.8/site-packages/flax/linen/transforms.py", line 1166, in wrapped_fn
    return prewrapped_fn(self, *args, **kwargs)
  File "/home/wilson/.local/lib/python3.8/site-packages/flax/linen/module.py", line 350, in wrapped_module_method
    return self._call_wrapped_method(fun, args, kwargs)
  File "/home/wilson/.local/lib/python3.8/site-packages/flax/linen/module.py", line 657, in _call_wrapped_method
    y = fun(self, *args, **kwargs)
  File "/home/wilson/.local/lib/python3.8/site-packages/flax/linen/linear.py", line 362, in __call__
    y = lax.conv_general_dilated(
  File "/home/wilson/.local/lib/python3.8/site-packages/jax/_src/lax/convolution.py", line 150, in conv_general_dilated
    return conv_general_dilated_p.bind(
  File "/home/wilson/.local/lib/python3.8/site-packages/jax/core.py", line 323, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/home/wilson/.local/lib/python3.8/site-packages/jax/core.py", line 326, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/home/wilson/.local/lib/python3.8/site-packages/jax/core.py", line 657, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/wilson/.local/lib/python3.8/site-packages/jax/_src/dispatch.py", line 96, in apply_primitive
    compiled_fun = xla_primitive_callable(prim, *unsafe_map(arg_spec, args),
  File "/home/wilson/.local/lib/python3.8/site-packages/jax/_src/util.py", line 213, in wrapper
    return cached(config._trace_context(), *args, **kwargs)
  File "/home/wilson/.local/lib/python3.8/site-packages/jax/_src/util.py", line 206, in cached
    return f(*args, **kwargs)
  File "/home/wilson/.local/lib/python3.8/site-packages/jax/_src/dispatch.py", line 115, in xla_primitive_callable
    compiled = _xla_callable_uncached(lu.wrap_init(prim_fun), device, None,
  File "/home/wilson/.local/lib/python3.8/site-packages/jax/_src/dispatch.py", line 176, in _xla_callable_uncached
    return lower_xla_callable(fun, device, backend, name, donated_invars,
  File "/home/wilson/.local/lib/python3.8/site-packages/jax/_src/dispatch.py", line 609, in compile
    self._executable = XlaCompiledComputation.from_xla_computation(
  File "/home/wilson/.local/lib/python3.8/site-packages/jax/_src/dispatch.py", line 696, in from_xla_computation
    compiled = compile_or_get_cached(backend, xla_computation, options)
  File "/home/wilson/.local/lib/python3.8/site-packages/jax/_src/dispatch.py", line 664, in compile_or_get_cached
    return backend_compile(backend, computation, compile_options)
  File "/home/wilson/.local/lib/python3.8/site-packages/jax/_src/profiler.py", line 206, in wrapper
    return func(*args, **kwargs)
  File "/home/wilson/.local/lib/python3.8/site-packages/jax/_src/dispatch.py", line 618, in backend_compile
    return backend.compile(built_c, compile_options=options)
jax._src.traceback_util.UnfilteredStackTrace: RuntimeError: UNKNOWN: -:4:130: error: expected '['

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test_flax.py", line 8, in <module>
    out = conv.init({'params': jax.random.PRNGKey(0)}, x)
  File "/home/wilson/.local/lib/python3.8/site-packages/flax/linen/linear.py", line 362, in __call__
    y = lax.conv_general_dilated(
RuntimeError: UNKNOWN: -:4:130: error: expected '['
```

**Comment by wilson1yan** [comment]
I don't think this is due to jax since the example script works fine (with various version of jax) if I revert to an older flax version, namely:
 `pip install git+https://github.com/google/flax.git@046174556fd7f4686fc8f15266e1a9479c1a1c5d`
(which I only happened to have due to an older conda env having a slightly older version of flax)

**Comment by jheek** [comment]
This was recently fixed. The next Flax release will support this syntax for now padding should be specified as padding=[(1, 1), (1, 1)] in this case.

**Comment by wilson1yan** [comment]
I see, thanks!
