### ISSUE TITLE
tabulate does not exist?

### ISSUE THREAD

**Issue by PhilipVinc** [google/flax#2160]
taken from the example

```python
>>> import jax
>>> import jax.numpy as jnp
>>> import flax
>>> import flax.linen as nn
>>>
>>> class Foo(nn.Module):
...     @nn.compact
...     def __call__(self, x):
...         h = nn.Dense(4)(x)
...         return nn.Dense(2)(h)
...
>>> x = jnp.ones((16, 9))
>>>
>>> print(Foo().tabulate(jax.random.PRNGKey(0), x))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/filippovicentini/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/flax/linen/module.py", line 714, in __getattr__
    raise AttributeError(
AttributeError: "Foo" object has no attribute "tabulate"
>>> flax.__version__
'0.5.0'
```

**Comment by PhilipVinc** [comment]
ah, my bad. It's not yet released
