### ISSUE TITLE
State sharing in `linen.map_Variables` between pre- and after- passes

### ISSUE THREAD

**Issue by PhilipVinc** [google/flax#2179]
I would like to take an arbitrary flax Module containing arbitrary complex `params` and convert it to a module that only has real `params`(real and imaginary part), but when applied he automatically repacks the real and imaginary part.

I already have an handy function to do that which operates on pytrees: it's called [`netket.jax.tree_to_real`](https://netket.readthedocs.io/en/latest/api/_generated/jax/netket.jax.tree_to_real.html?highlight=tree_to_Real#netket.jax.tree_to_real). I need to lift it to a flax Module.

netket.jax.tree_to_Real takes a PyTree and returns a new pytree with only real parameters, and a function to convert the output back to the original form:

```python
In [74]: import jax.numpy as jnp; import netket as nk

In [75]: pars = {'a': jnp.ones((3,2))-1j*jnp.ones((3,2)), 'b':jnp.ones(4)}

In [76]: pars_r, repack = nk.jax.tree_to_real(pars)

In [77]: pars_r
Out[77]:
{'a': (DeviceArray([[1., 1.],
               [1., 1.],
               [1., 1.]], dtype=float64),
  DeviceArray([[-1., -1.],
               [-1., -1.],
               [-1., -1.]], dtype=float64)),
 'b': DeviceArray([1., 1., 1., 1.], dtype=float64)}

In [79]: repack(pars_r)
Out[79]:
{'a': DeviceArray([[1.-1.j, 1.-1.j],
              [1.-1.j, 1.-1.j],
              [1.-1.j, 1.-1.j]], dtype=complex128),
 'b': DeviceArray([1., 1., 1., 1.], dtype=float64)}

```

I decided to try using `linen.map_variables` to achieve my target:

```python
import netket as nk
from functools import partial

class RealDense(nn.Module):
  @nn.compact
  def __call__(self, x):
    reco = None
    def trans_in_fn(x):
      print("trans_in_fn", jax.tree_map(lambda x: f"{x.dtype}:{x.shape}", x))
      nonlocal reco
      return reco(x)
    def trans_out_fn(x):
      print("trans_out_fn x:", jax.tree_map(lambda x: f"{x.dtype}:{x.shape}", x))
      nonlocal reco
      xr, reco = nk.jax.tree_to_real(x)
      print("unpacked x is: ", jax.tree_map(lambda x: f"{x.dtype}:{x.shape}", xr))
      return xr
    MapDense = nn.map_variables(nn.Dense, "params", trans_in_fn, trans_out_fn, init=True)
    return MapDense(4, param_dtype=complex)(x)

x = jax.numpy.ones((2,3))
y, pars = RealDense().init_with_output(jax.random.PRNGKey(0), x)
y, pars

RealDense().apply(pars, x)
```

As you see, I need to share the `reco` variable from the unpack function. 
This all works fine when running initialise, because it first calls `unpack` and then `repack`, but fails when doing `apply` because it calls only the latter.

```python
    ...: x = jax.numpy.ones((2,3))
    ...: y, pars = RealDense().init_with_output(jax.random.PRNGKey(0), x)
    ...: y, pars
    ...:
trans_out_fn x: {'params': {'bias': 'complex128:(4,)', 'kernel': 'complex128:(3, 4)'}}
unpacked x is:  {'params': {'bias': ('float64:(4,)', 'float64:(4,)'), 'kernel': ('float64:(3, 4)', 'float64:(3, 4)')}}
trans_in_fn {'params': {'bias': ('float64:(4,)', 'float64:(4,)'), 'kernel': ('float64:(3, 4)', 'float64:(3, 4)')}}
trans_out_fn x: {'params': {'bias': 'complex128:(4,)', 'kernel': 'complex128:(3, 4)'}}
unpacked x is:  {'params': {'bias': ('float64:(4,)', 'float64:(4,)'), 'kernel': ('float64:(3, 4)', 'float64:(3, 4)')}}
Out[93]:
(DeviceArray([[0.45394734-1.78661668j, 0.72233656+0.84126228j,
               0.0538656 +0.5807597j , 0.68782575+0.76725457j],
              [0.45394734-1.78661668j, 0.72233656+0.84126228j,
               0.0538656 +0.5807597j , 0.68782575+0.76725457j]],            dtype=complex128),
 FrozenDict({
     params: {
         Map_variablesDense_0: {
             bias: (DeviceArray([0., 0., 0., 0.], dtype=float64), DeviceArray([-0., -0., -0., -0.], dtype=float64)),
             kernel: (DeviceArray([[ 0.84231832, -0.31733174, -0.68592991,  0.54918591],
                          [-0.09233927,  0.75760892,  0.44805401, -0.25425447],
                          [-0.29603172,  0.28205938,  0.29174151,  0.39289431]],            dtype=float64), DeviceArray([[-0.59764332,  0.34293384, -0.69193288,  0.19731981],
                          [-0.34537935,  0.25073421,  0.705592  ,  0.85386235],
                          [-0.84359401,  0.24759423,  0.56710058, -0.28392759]],            dtype=float64)),
         },
     },
 }))
```

but if I call apply, this fails because `reco` is not defined in the scope. 
```python
In [94]: RealDense().apply(pars, x)
    ...:
trans_in_fn {'params': {'bias': ('float64:(4,)', 'float64:(4,)'), 'kernel': ('float64:(3, 4)', 'float64:(3, 4)')}}
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [94], in <cell line: 1>()
----> 1 RealDense().apply(pars, x)

    [... skipping hidden 7 frame]

Input In [92], in RealDense.__call__(self, x)
     17   return xr
     18 MapDense = nn.map_variables(nn.Dense, "params", trans_in_fn, trans_out_fn, init=True)
---> 19 return MapDense(4, param_dtype=complex)(x)

    [... skipping hidden 5 frame]

Input In [92], in RealDense.__call__.<locals>.repack(x)
      9 print("trans_in_fn", jax.tree_map(lambda x: f"{x.dtype}:{x.shape}", x))
     10 nonlocal reco
---> 11 return reco(x)

TypeError: 'NoneType' object is not callable
```

Is there a mechanism by which I could share some context between the scopes?

**Comment by PhilipVinc** [comment]
edit: If you don't want to install netket, a smaller MWE is the following:

```python
import jax.numpy as jnp
import jax
import flax
import flax.linen as nn

def tree_to_real(x):
   return x, lambda x: x

class RealDense(nn.Module):
  @nn.compact
  def __call__(self, x):
    reco = None
    def repack(x):
      nonlocal reco
      return reco(x)
    def unpack(x):
      nonlocal reco
      xr, reco = tree_to_real(x)
      return xr
    MapDense = nn.map_variables(nn.Dense, "params", repack, unpack, init=True)
    return MapDense(4, param_dtype=complex)(x)

x = jax.numpy.ones((2,3))
y, pars = RealDense().init_with_output(jax.random.PRNGKey(0), x)
y, pars

RealDense().apply(pars, x)

```

**Comment by cgarciae** [comment]
@PhilipVinc I am getting this error in your last example:

```
Traceback (most recent call last):
  File "tmp/complex.py", line 27, in <module>
    c = RealDense().apply(pars, x)
  File "tmp/complex.py", line 21, in __call__
    return MapDense(4, param_dtype=complex)(x)
  File "tmp/complex.py", line 15, in repack
    return reco(x)
TypeError: 'NoneType' object is not callable
```

**Comment by PhilipVinc** [comment]
Yes exactly that's my point. 
It errors when applying but not when initializing it, because the reco variable is not correctly setup.

I'd like to make it work on apply too...

Im in my phone now. I'll maybe try to better rephrase what my issue is later tonight

**Comment by PhilipVinc** [comment]
So, if you tun my example above without the last line, that is:

```python
import jax.numpy as jnp
import jax
import flax
import flax.linen as nn

def tree_to_real(x):
   return x, lambda x: x

class RealDense(nn.Module):
  @nn.compact
  def __call__(self, x):
    reco = None
    def repack(x):
      nonlocal reco
      return reco(x)
    def unpack(x):
      nonlocal reco
      xr, reco = tree_to_real(x)
      return xr
    MapDense = nn.map_variables(nn.Dense, "params", repack, unpack, init=True)
    return MapDense(4, param_dtype=complex)(x)

x = jax.numpy.ones((2,3))
y, pars = RealDense().init_with_output(jax.random.PRNGKey(0), x)
```

it runs fine, right?

Looking at the signature of [`linen.map_variables(target, mapped_collection, trans_in_fn , trans_out_fn)`](https://flax.readthedocs.io/en/latest/_autosummary/flax.linen.map_variables.html#flax.linen.map_variables), I eventually understood that the two `trans_in_fn` and `trans_out_fn` are vaguely equivalent to doing the following:

```python
transformed_module = linen.map_variables(target, mapped_collection, trans_in_fn , trans_out_fn)

transformed_pars = transformed_module.init(rng, x)
transformed_y = transformed_module.apply(transformed_pars, x)

pars = trans_out_fn(target.init(rng, x))
y = target.apply(trans_in_fn(pars), x)

assert transformed_pars == pars
assert y == transformed_y
```

Is my understanding correct?

Now, from this picture it should be clear that   `trans_out_fn` is only executed once, when initialising the parameters, while `trans_in_fn` is executed at every apply.
What I need to do is to pass some information/statefrom `trans_out_fn` to `trans_in_fn`, effectively doing something like

```python
pars, trans_state = trans_out_fn(target.init(rng, x))
y = target.apply(trans_in_fn(pars, trans_state), x)
```

but that is not supported by the current flax syntax.

In my sample code above (I renamed unpack and repack to `trans_out_fn` and `trans_in_fn` for better clarity) I managed to pass some state with some hack mechanism, but that does not work well and it would be great to have a more standard way to do that.

Is that explanation more clear?

**Comment by jheek** [comment]
Don't you essentially want this? 

```python
class ReIm(flax.struct.PyTreeNode):
  re: Any
  im: Any

  def unpack():
    return self.re + 1j * self.im

def imag_to_real(xs):
  return jax.tree_map(lambda x: ReIm(x.real, x.imag), xs

def unpack(xs):
  def f(x):
    if isinstance(x, ReIm):
     return x.unpack()
    return x
  return jax.tree_map(f, xs, is_leaf=isinstance(x, ReIm)

MapDense = nn.map_variables(nn.Dense, "params", trans_in_fn=unpack, trans_out_fn=imag_to_real, mutable=True)
```

**Comment by jheek** [comment]
Closing due to lack of activity, feel free to re-open if necessary
