### ISSUE TITLE
IPython autoreload is not supported by flax

### ISSUE THREAD

**Issue by n-gao** [google/flax#2286]
### System information
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Flax, jax, jaxlib versions (obtain with `pip show flax jax jaxlib`: flax 0.4, jax 0.3.1, jaxlib 0.30 (cuda11)
- Python version:  3.8
- GPU/TPU model and memory: GTX 1080ti
- CUDA version (if applicable): 11

### Problem you have encountered:
If you want to prototype in a file and use the `autoreload` package of `ipython`, anytime you edit a file with a flax linen module you get an error.
```python
%load_ext autoreload
%autoreload 2
<load file>
<edit file>
<call any new cell>
```
A workaround would be to copy the file content to a jupyter notebook cell and copy it back when the edits have been done.

### What you expected to happen:
The expected behavior would be that either the module class changes. I guess this behavior conflicts with linen foundations, maybe it is easier to implement it such that the newly created instances adopt the updated implementation?

### Logs, error messages, etc:
```python
[autoreload of mabenet.nn.ferminet failed: Traceback (most recent call last):
  File "/nfs/staff-ssd/gaoni/miniconda3/envs/pesnet/lib/python3.8/site-packages/IPython/extensions/autoreload.py", line 257, in check
    superreload(m, reload, self.old_objects)
  File "/nfs/staff-ssd/gaoni/miniconda3/envs/pesnet/lib/python3.8/site-packages/IPython/extensions/autoreload.py", line 480, in superreload
    update_generic(old_obj, new_obj)
  File "/nfs/staff-ssd/gaoni/miniconda3/envs/pesnet/lib/python3.8/site-packages/IPython/extensions/autoreload.py", line 377, in update_generic
    update(a, b)
  File "/nfs/staff-ssd/gaoni/miniconda3/envs/pesnet/lib/python3.8/site-packages/IPython/extensions/autoreload.py", line 345, in update_class
    update_instances(old, new)
  File "/nfs/staff-ssd/gaoni/miniconda3/envs/pesnet/lib/python3.8/site-packages/IPython/extensions/autoreload.py", line 303, in update_instances
    ref.__class__ = new
  File "/nfs/staff-ssd/gaoni/miniconda3/envs/pesnet/lib/python3.8/site-packages/flax/linen/module.py", line 669, in __setattr__
    raise errors.SetAttributeFrozenModuleError(self.__class__.__name__, name,
flax.errors.SetAttributeFrozenModuleError: Can't set __class__=<class 'ferminet.FeatureConstruction'> for Module of type FeatureConstruction: Module instance is frozen outside of setup method. (https://flax.readthedocs.io/en/latest/flax.errors.html#flax.errors.SetAttributeFrozenModuleError)
]
```

**Comment by cgarciae** [comment]
We tried to reproduce some this issue but since no instructions where provided we tested with this setup:

```python
# my_module.py
import flax.linen as nn
from flax.struct import PyTreeNode

class MyModule(nn.Module):
    def setup(self):
        self.dense = nn.Dense(10)
        
    def __call__(self, x):
        return self.dense(x)

class MyPyTreeNode(PyTreeNode):
    a: int = 3

module = MyModule()
tree = MyPyTreeNode()
```
```python
# test.ipynb
%load_ext autoreload
%autoreload 2

from my_module import MyModule, module, MyPyTreeNode, tree
```
We did find an issue that is being addressed in #2548 but its not the same as originally reported, after that was fixed no other issue was found. I'll be closing this issue for now as I didn't find anything. Feel free to re-open it if the issue is still there.

**Comment by n-gao** [comment]
@cgarciae Thanks for looking into this. After playing around a bit I noticed that the error is due to `nn.compact`. Here's an example to reproduce the issue:

```python
# my_module.py
import flax.linen as nn

class MyModule(nn.Module):
    def setup(self):
        self.dense = nn.Dense(10)
        
    def __call__(self, x):
        return self.dense(x)


#class MyModule(nn.Module):
#    @nn.compact
#    def __call__(self, x):
#        return nn.Dense(10)(x)

```
```python
# test.ipynb
### Cell 1
%load_ext autoreload
%autoreload 2
from my_module import MyModule

### Cell 2
model = MyModule()
params = model.init(jax.random.PRNGKey(42), jnp.ones((10,))

# Now edit my_module by uncommenting the `nn.compact` implementation.

### Cell 3
model = MyModule()
params = model.init(jax.random.PRNGKey(42), jnp.ones((10,))
```

Output:
```python
[autoreload of my_module failed: Traceback (most recent call last):
  File "/nfs/staff-ssd/gaoni/miniconda3/envs/jax0317/lib/python3.9/site-packages/IPython/extensions/autoreload.py", line 257, in check
    superreload(m, reload, self.old_objects)
  File "/nfs/staff-ssd/gaoni/miniconda3/envs/jax0317/lib/python3.9/site-packages/IPython/extensions/autoreload.py", line 480, in superreload
    update_generic(old_obj, new_obj)
  File "/nfs/staff-ssd/gaoni/miniconda3/envs/jax0317/lib/python3.9/site-packages/IPython/extensions/autoreload.py", line 377, in update_generic
    update(a, b)
  File "/nfs/staff-ssd/gaoni/miniconda3/envs/jax0317/lib/python3.9/site-packages/IPython/extensions/autoreload.py", line 329, in update_class
    if update_generic(old_obj, new_obj):
  File "/nfs/staff-ssd/gaoni/miniconda3/envs/jax0317/lib/python3.9/site-packages/IPython/extensions/autoreload.py", line 377, in update_generic
    update(a, b)
  File "/nfs/staff-ssd/gaoni/miniconda3/envs/jax0317/lib/python3.9/site-packages/IPython/extensions/autoreload.py", line 289, in update_function
    setattr(old, name, getattr(new, name))
ValueError: setup() requires a code object with 1 free vars, not 0
]
```
