### ISSUE TITLE
Error checkpointing model after training for a while on TPU v3-32

### ISSUE THREAD

**Issue by jenkspt** [google/flax#2600]
Provide as much information as possible. At least, this should include a description of your issue and steps to reproduce the problem. If possible also provide a summary of what steps or workarounds you have already tried.

### System information
- TPU Version: `tpu-vm-base`
- TPU model: v3-32

### Problem you have encountered:
using `flax.checkpoints.save_checkpoint` with `keep=6` I save a checkpoint every 10,000 steps, which works fine for the first 6 checkpoints, but then seems to throw an error when removing the old checkpoint. Not why there is `tcmalloc: large alloc`

Running locally on GPU the checkpointing works as expected

### Logs, error messages, etc:
```
...
INFO:root:step = 70000, lr = 0.000007, loss = (value=0.028040, ema=0.026814)
tcmalloc: large alloc 2285002752 bytes == 0x529bfe000 @  0x7f7b7a980680 0x7f7b7a9a0bdd 0x7f7b6194126f 0x7f7b61950290 0x7f7b61951324 0x7f7b61951324 0x7f7b61951324 0x7f7b61951324 0x7f7b61951324 0x7f7b61951324 0x7f7b61951324 0x7f7b6194bd74 0x7f7b6194c52e 0x503fb6 0x56b1da 0x56939a 0x5f6a13 0x56c28c 0x56939a 0x5f6a13 0x570035 0x56939a 0x5f6a13 0x56c28c 0x56939a 0x5f6a13 0x5f3547 0x56c8cd 0x56939a 0x5f6a13 0x56c28c
tcmalloc: large alloc 2285002752 bytes == 0x5259b4000 @  0x7f7ab6620680 0x7f7ab6640bdd 0x7f7aa5f4826f 0x7f7aa5f57290 0x7f7aa5f58324 0x7f7aa5f58324 0x7f7aa5f58324 0x7f7aa5f58324 0x7f7aa5f58324 0x7f7aa5f58324 0x7f7aa5f58324 0x7f7aa5f52d74 0x7f7aa5f5352e 0x503fb6 0x56b1da 0x56939a 0x5f6a13 0x56c28c 0x56939a 0x5f6a13 0x570035 0x56939a 0x5f6a13 0x56c28c 0x56939a 0x5f6a13 0x5f3547 0x56c8cd 0x56939a 0x5f6a13 0x56c28c
tcmalloc: large alloc 2285002752 bytes == 0x53ff46000 @  0x7f4a708ad680 0x7f4a708cdbdd 0x7f4a5ae9326f 0x7f4a5aea2290 0x7f4a5aea3324 0x7f4a5aea3324 0x7f4a5aea3324 0x7f4a5aea3324 0x7f4a5aea3324 0x7f4a5aea3324 0x7f4a5aea3324 0x7f4a5ae9dd74 0x7f4a5ae9e52e 0x503fb6 0x56b1da 0x56939a 0x5f6a13 0x56c28c 0x56939a 0x5f6a13 0x570035 0x56939a 0x5f6a13 0x56c28c 0x56939a 0x5f6a13 0x5f3547 0x56c8cd 0x56939a 0x5f6a13 0x56c28c
tcmalloc: large alloc 2285002752 bytes == 0x56cbe4000 @  0x7f591a26b680 0x7f591a28bbdd 0x7f590885726f 0x7f5908866290 0x7f5908867324 0x7f5908867324 0x7f5908867324 0x7f5908867324 0x7f5908867324 0x7f5908867324 0x7f5908867324 0x7f5908861d74 0x7f590886252e 0x503fb6 0x56b1da 0x56939a 0x5f6a13 0x56c28c 0x56939a 0x5f6a13 0x570035 0x56939a 0x5f6a13 0x56c28c 0x56939a 0x5f6a13 0x5f3547 0x56c8cd 0x56939a 0x5f6a13 0x56c28c
tcmalloc: large alloc 4578607104 bytes == 0x5b1f24000 @  0x7f7b7a980680 0x7f7b7a9a0bdd 0x7f7b6194126f 0x7f7b61950290 0x7f7b61951324 0x7f7b61951324 0x7f7b61951324 0x7f7b61951324 0x7f7b61951324 0x7f7b61951324 0x7f7b61951324 0x7f7b6194bd74 0x7f7b6194c52e 0x503fb6 0x56b1da 0x56939a 0x5f6a13 0x56c28c 0x56939a 0x5f6a13 0x570035 0x56939a 0x5f6a13 0x56c28c 0x56939a 0x5f6a13 0x5f3547 0x56c8cd 0x56939a 0x5f6a13 0x56c28c
tcmalloc: large alloc 4578607104 bytes == 0x5adcda000 @  0x7f7ab6620680 0x7f7ab6640bdd 0x7f7aa5f4826f 0x7f7aa5f57290 0x7f7aa5f58324 0x7f7aa5f58324 0x7f7aa5f58324 0x7f7aa5f58324 0x7f7aa5f58324 0x7f7aa5f58324 0x7f7aa5f58324 0x7f7aa5f52d74 0x7f7aa5f5352e 0x503fb6 0x56b1da 0x56939a 0x5f6a13 0x56c28c 0x56939a 0x5f6a13 0x570035 0x56939a 0x5f6a13 0x56c28c 0x56939a 0x5f6a13 0x5f3547 0x56c8cd 0x56939a 0x5f6a13 0x56c28c
tcmalloc: large alloc 4578607104 bytes == 0x5c826c000 @  0x7f4a708ad680 0x7f4a708cdbdd 0x7f4a5ae9326f 0x7f4a5aea2290 0x7f4a5aea3324 0x7f4a5aea3324 0x7f4a5aea3324 0x7f4a5aea3324 0x7f4a5aea3324 0x7f4a5aea3324 0x7f4a5aea3324 0x7f4a5ae9dd74 0x7f4a5ae9e52e 0x503fb6 0x56b1da 0x56939a 0x5f6a13 0x56c28c 0x56939a 0x5f6a13 0x570035 0x56939a 0x5f6a13 0x56c28c 0x56939a 0x5f6a13 0x5f3547 0x56c8cd 0x56939a 0x5f6a13 0x56c28c
tcmalloc: large alloc 4578607104 bytes == 0x5f4f0a000 @  0x7f591a26b680 0x7f591a28bbdd 0x7f590885726f 0x7f5908866290 0x7f5908867324 0x7f5908867324 0x7f5908867324 0x7f5908867324 0x7f5908867324 0x7f5908867324 0x7f5908867324 0x7f5908861d74 0x7f590886252e 0x503fb6 0x56b1da 0x56939a 0x5f6a13 0x56c28c 0x56939a 0x5f6a13 0x570035 0x56939a 0x5f6a13 0x56c28c 0x56939a 0x5f6a13 0x5f3547 0x56c8cd 0x56939a 0x5f6a13 0x56c28c
tcmalloc: large alloc 3562586112 bytes == 0x6c35a4000 @  0x7f7b7a980680 0x7f7b7a9a1824 0x5f8a01 0x7f7b6194be19 0x7f7b6194c52e 0x503fb6 0x56b1da 0x56939a 0x5f6a13 0x56c28c 0x56939a 0x5f6a13 0x570035 0x56939a 0x5f6a13 0x56c28c 0x56939a 0x5f6a13 0x5f3547 0x56c8cd 0x56939a 0x5f6a13 0x56c28c 0x56939a 0x5f6a13 0x56b0ae 0x56939a 0x5f6a13 0x570035 0x56939a 0x68d047
tcmalloc: large alloc 3562586112 bytes == 0x6bf35a000 @  0x7f7ab6620680 0x7f7ab6641824 0x5f8a01 0x7f7aa5f52e19 0x7f7aa5f5352e 0x503fb6 0x56b1da 0x56939a 0x5f6a13 0x56c28c 0x56939a 0x5f6a13 0x570035 0x56939a 0x5f6a13 0x56c28c 0x56939a 0x5f6a13 0x5f3547 0x56c8cd 0x56939a 0x5f6a13 0x56c28c 0x56939a 0x5f6a13 0x56b0ae 0x56939a 0x5f6a13 0x570035 0x56939a 0x68d047
tcmalloc: large alloc 3562586112 bytes == 0x6d98ec000 @  0x7f4a708ad680 0x7f4a708ce824 0x5f8a01 0x7f4a5ae9de19 0x7f4a5ae9e52e 0x503fb6 0x56b1da 0x56939a 0x5f6a13 0x56c28c 0x56939a 0x5f6a13 0x570035 0x56939a 0x5f6a13 0x56c28c 0x56939a 0x5f6a13 0x5f3547 0x56c8cd 0x56939a 0x5f6a13 0x56c28c 0x56939a 0x5f6a13 0x56b0ae 0x56939a 0x5f6a13 0x570035 0x56939a 0x68d047
tcmalloc: large alloc 3562586112 bytes == 0x70658a000 @  0x7f591a26b680 0x7f591a28c824 0x5f8a01 0x7f5908861e19 0x7f590886252e 0x503fb6 0x56b1da 0x56939a 0x5f6a13 0x56c28c 0x56939a 0x5f6a13 0x570035 0x56939a 0x5f6a13 0x56c28c 0x56939a 0x5f6a13 0x5f3547 0x56c8cd 0x56939a 0x5f6a13 0x56c28c 0x56939a 0x5f6a13 0x56b0ae 0x56939a 0x5f6a13 0x570035 0x56939a 0x68d047
INFO:absl:Saving checkpoint at step: 70000
INFO:absl:Saving checkpoint at step: 70000
INFO:absl:Saving checkpoint at step: 70000
INFO:absl:Saving checkpoint at step: 70000
INFO:absl:Saved checkpoint at gs://smol-imagen/runs/testrun_mscoco3/checkpoints/train_state/checkpoint_70000
INFO:absl:Removing checkpoint at gs://smol-imagen/runs/testrun_mscoco3/checkpoints/train_state/checkpoint_10000
Traceback (most recent call last):
  File "train/train.py", line 237, in <module>
    fire.Fire(main)
  File "/home/penn/.local/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/penn/.local/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/penn/.local/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "train/train.py", line 221, in main
    checkpoints.save_checkpoint_multiprocess(
  File "/home/penn/.local/lib/python3.8/site-packages/flax/training/checkpoints.py", line 619, in save_checkpoint_multiprocess
    save_main_ckpt_task()
  File "/home/penn/.local/lib/python3.8/site-packages/flax/training/checkpoints.py", line 611, in save_main_ckpt_task
    return _save_main_ckpt_file(target, has_mpa, (ckpt_tmp_path, ckpt_path),
  File "/home/penn/.local/lib/python3.8/site-packages/flax/training/checkpoints.py", line 461, in _save_main_ckpt_file
    _save_commit(
  File "/home/penn/.local/lib/python3.8/site-packages/flax/training/checkpoints.py", line 420, in _save_commit
    _remove_invalid_ckpts(ckpt_path, base_path, keep, overwrite,
  File "/home/penn/.local/lib/python3.8/site-packages/flax/training/checkpoints.py", line 380, in _remove_invalid_ckpts
    gfile.rmtree(path)
  File "/home/penn/.local/lib/python3.8/site-packages/tensorflow/python/lib/io/file_io.py", line 674, in delete_recursively_v2
    _pywrap_file_io.DeleteRecursively(compat.path_to_bytes(path))
tensorflow.python.framework.errors_impl.NotFoundError: gs://smol-imagen/runs/testrun_mscoco3/checkpoints/train_state/checkpoint_10000 doesn't exist or not a directory.
```

### Steps to reproduce:
Repository is currently private, but here's the checkpointing code
```python
  if (step > 0) and (step % checkpoint_frequency == 0):
      dataset_manager.save(step)  # save dataset state in each process
      # save train state in process 0
      checkpoints.save_checkpoint_multiprocess(
          f'{working_dir}/checkpoints/train_state',
          unreplicate(train_state), step, keep=keep_checkpoints)
```

**Comment by IvyZX** [comment]
This should be fixed by https://github.com/google/flax/pull/2518, which was not released yet. We probably should release another round...

Would you like to try installing Flax from head and see if this problem goes away? Just to make sure the PR solves your issue.

**Comment by jenkspt** [comment]
Sure! I'll give it a try.
