### ISSUE TITLE
AssertionError: sync_global_devices name mismatch ('starting_save_checkpoint')

### ISSUE THREAD

**Issue by jenkspt** [google/flax#2834]
### System information
- OS: Ubuntu 20.04.4 LTS
- jax==0.4.2
- jaxlib==0.4.2
- flax==0.6.4
- tensorflow==2.11.0
- TPU v3-32 (v2-tf-stable)
- Python version: 3.8.10

### Problem you have encountered:
get `AssertionError: sync_global_devices name mismatch ('starting_save_checkpoint') Expected: 1127039785; got: -1219314350`
when training script tries to save 3rd checkpoint (when keep=3).
training script: [https://github.com/jenkspt/gpt-jax/blob/4f15ff3826e82d5c94f5170bccae4f2413d40344/train.py](https://github.com/jenkspt/gpt-jax/blob/4f15ff3826e82d5c94f5170bccae4f2413d40344/train.py)
checkpoint saving line: [https://github.com/jenkspt/gpt-jax/blob/4f15ff3826e82d5c94f5170bccae4f2413d40344/train.py#L209-L212](https://github.com/jenkspt/gpt-jax/blob/4f15ff3826e82d5c94f5170bccae4f2413d40344/train.py#L209-L212)

### What you expected to happen:
Save the checkpoint successfully from process 0. It's curious that the error shows worker 3 failing.

### Logs, error messages, etc:
```
Traceback (most recent call last):
  File "train.py", line 209, in <module>
    checkpoints.save_checkpoint_multiprocess(
  File "/home/penn/.local/lib/python3.8/site-packages/flax/training/checkpoints.py", line 657, in save_checkpoint_multiprocess
    sync_global_devices('starting_save_checkpoint')
  File "/home/penn/.local/lib/python3.8/site-packages/jax/experimental/multihost_utils.py", line 87, in sync_global_devices
    assert_equal(h, f"sync_global_devices name mismatch ('{name}')")
  File "/home/penn/.local/lib/python3.8/site-packages/jax/experimental/multihost_utils.py", line 183, in assert_equal
    raise AssertionError(
AssertionError: sync_global_devices name mismatch ('starting_save_checkpoint') Expected: 1127039785; got: -1219314350.
##### Command execution on worker 3 failed with exit status 1. Continuing.
E0201 19:17:04.312397    4542 coredump_hook.cc:414] RAW: Remote crash data gathering hook invoked.
E0201 19:17:04.312420    4542 coredump_hook.cc:453] RAW: Called via ReportEvent and disabled coredump
E0201 19:17:04.312440    4542 client.cc:277] RAW: Coroner client retries enabled (b/136286901), will retry for up to 30 sec.
E0201 19:17:04.312445    4542 coredump_hook.cc:512] RAW: Sending fingerprint to remote end.
E0201 19:17:04.312451    4542 coredump_socket.cc:120] RAW: Stat failed errno=2 on socket /var/google/services/logmanagerd/remote_coredump.socket
E0201 19:17:04.312455    4542 coredump_hook.cc:518] RAW: Cannot send fingerprint to Coroner: [NOT_FOUND] Missing crash reporting socket. Is the listener running?
E0201 19:17:04.312458    4542 coredump_hook.cc:580] RAW: Dumping core locally.
```

**Comment by IvyZX** [comment]
I'm so sorry for the late reply - this somehow fell through the cracks. A few questions/thoughts:

1. Does the error happen every time the checkpoint is saved? Or only the third time?

1. It looks like you `unreplicate` the TrainState and only save from process 0, in which case you might want to use `save_checkpoint()` instead of `save_checkpoint_multiprocess()`. The latter is for arrays that was sharded distributedly (usually generated from `pjit()`).

Let me know if that helps!

**Comment by jenkspt** [comment]
Np. Thanks for the reply.
The error only happens when saving the 3rd time -- not sure if that's related to keep checkpoint frequency. Also saving to gcs if that makes a difference.

Are you saying that if I use `save_checkpoint_multiprocess()` I shouldn't use `unreplicate` prior to saving?

Also I should note that I was having a similar problem previously: https://github.com/google/flax/issues/2600

**Comment by IvyZX** [comment]
Closing issue due to inactivity.
