### ISSUE TITLE
Flax submodule attribute not found in flax.linen.scan

### ISSUE THREAD

**Issue by jamesheald** [google/flax#3361]
I am declaring a linen submodule named MLP as an attribute of another module named OuterLoop (as per [here](https://github.com/google/flax/issues/818)). When I call MLP via flax.linen.scan (in the InnerLoop function),  I get an error saying that the dense attribute of MLP does not exist.

What is the problem here and how I can get around it?

Here is a MWE (the semantics of the code can be ignored)

```
from flax import linen as nn
import jax

class MLP(nn.Module):
    def setup(self):
        self.dense = nn.Dense(3)
    def __call__(self, x):
        return self.dense(x)

class OuterLoop(nn.Module):
    mlp: MLP
    def setup(self):
        None
    def __call__(self, carry, inputs):
        def InnerLoop(module, carry, inputs):
            carry = self.mlp(carry)
            return carry, carry
        carry, outputs = nn.scan(InnerLoop, variable_broadcast = 'params', split_rngs = {"params": False})(self.mlp, carry, inputs)
        return carry, outputs

class Dummy(nn.Module):
    def setup(self):
        self.mlp = MLP()
        scanner = nn.scan(OuterLoop, variable_broadcast = 'params', split_rngs = {"params": False})
        self.scanner = scanner(self.mlp)
    def __call__(self, carry, inputs):
        carry, outputs = self.scanner(carry, inputs)
        return self.mlp(carry) + carry

dummy = Dummy()
init_vars = dummy.init(carry = jax.numpy.ones((2,3)), inputs = jax.numpy.ones((2,3)), rngs = {'params': jax.random.PRNGKey(0)})
dummy.apply(init_vars, carry = jax.numpy.ones((2,3)), inputs = jax.numpy.ones((2,3)))
```

Here is the Traceback

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test2.py", line 31, in <module>
    init_vars = dummy.init(carry = jax.numpy.ones((2,3)), inputs = jax.numpy.ones((2,3)), rngs = {'params': jax.random.PRNGKey(0)})
  File "test2.py", line 27, in __call__
    carry, outputs = self.scanner(carry, inputs)
  File "/nfs/nhome/live/jheald/.local/lib/python3.8/site-packages/flax/core/axes_scan.py", line 139, in scan_fn
    _, out_pvals, _ = pe.trace_to_jaxpr_nounits(f_flat, in_pvals)
  File "/nfs/nhome/live/jheald/.local/lib/python3.8/site-packages/flax/core/axes_scan.py", line 115, in body_fn
    broadcast_out, c, ys = fn(broadcast_in, c, *xs)
  File "test2.py", line 18, in __call__
    carry, outputs = nn.scan(InnerLoop, variable_broadcast = 'params', split_rngs = {"params": False})(self.mlp, carry, inputs)
  File "/nfs/nhome/live/jheald/.local/lib/python3.8/site-packages/flax/core/axes_scan.py", line 139, in scan_fn
    _, out_pvals, _ = pe.trace_to_jaxpr_nounits(f_flat, in_pvals)
  File "/nfs/nhome/live/jheald/.local/lib/python3.8/site-packages/flax/core/axes_scan.py", line 115, in body_fn
    broadcast_out, c, ys = fn(broadcast_in, c, *xs)
  File "test2.py", line 16, in InnerLoop
    carry = self.mlp(carry)
  File "test2.py", line 8, in __call__
    return self.dense(x)
AttributeError: "MLP" object has no attribute "dense".
```

**Comment by jamesheald** [comment]
I noticed that this error didn't happen when I ran this code on another computer. I upgraded flax (from 0.6.10 to 0.7.2) and the error has gone away.
