### ISSUE TITLE
Bug in guide "Scale up Flax Modules on multiple devices" flax.errors.InvalidRngError: RNGs should be of shape (2,)

### ISSUE THREAD

**Issue by PawKanarek** [google/flax#3532]
Hello
while i was was following steps from https://flax.readthedocs.io/en/latest/guides/parallel_training/flax_on_pjit.html on Google TPU's v3-8 i encoured an error `flax.errors.InvalidRngError: RNGs should be of shape (2,)`

At first i thought i made some spelling mistake while retyping guide, but, when i copied-pasted all parts into my script, then error still occurs

### Logs, error messages, etc:
```
(tmp) raix@t1v-n-d3214137-w-0:/mnt/disks/persist/repos$ python diffusers/examples/text_to_image/test_resource_exhausted.py 
WARNING:absl:Tensorflow library not found, tensorflow.io.gfile operations will use native shim calls. GCS paths (i.e. 'gs://...') cannot be accessed.
[TpuDevice(id=0, process_index=0, coords=(0,0,0), core_on_chip=0), TpuDevice(id=1, process_index=0, coords=(0,0,0), core_on_chip=1), TpuDevice(id=2, process_index=0, coords=(1,0,0), core_on_chip=0), TpuDevice(id=3, process_index=0, coords=(1,0,0), core_on_chip=1), TpuDevice(id=4, process_index=0, coords=(0,1,0), core_on_chip=0), TpuDevice(id=5, process_index=0, coords=(0,1,0), core_on_chip=1), TpuDevice(id=6, process_index=0, coords=(1,1,0), core_on_chip=0), TpuDevice(id=7, process_index=0, coords=(1,1,0), core_on_chip=1)]
[[TpuDevice(id=0, process_index=0, coords=(0,0,0), core_on_chip=0)
  TpuDevice(id=1, process_index=0, coords=(0,0,0), core_on_chip=1)
  TpuDevice(id=2, process_index=0, coords=(1,0,0), core_on_chip=0)
  TpuDevice(id=3, process_index=0, coords=(1,0,0), core_on_chip=1)]
 [TpuDevice(id=6, process_index=0, coords=(1,1,0), core_on_chip=0)
  TpuDevice(id=7, process_index=0, coords=(1,1,0), core_on_chip=1)
  TpuDevice(id=4, process_index=0, coords=(0,1,0), core_on_chip=0)
  TpuDevice(id=5, process_index=0, coords=(0,1,0), core_on_chip=1)]]
Mesh(device_ids=array([[0, 1, 2, 3],
       [6, 7, 4, 5]]), axis_names=('data', 'model'))
┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│                                 TPU 0,1,2,3                                  │
│                                                                              │
│                                                                              │
├──────────────────────────────────────────────────────────────────────────────┤
│                                                                              │
│                                 TPU 4,5,6,7                                  │
│                                                                              │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "diffusers/examples/text_to_image/test_resource_exhausted.py", line 123, in <module>
    main()
  File "diffusers/examples/text_to_image/test_resource_exhausted.py", line 114, in main
    abstract_variables = jax.eval_shape(functools.partial(init_fn, model=model, optimizer=optimizer), k, x)
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/jax/_src/api.py", line 2783, in eval_shape
    out = pe.abstract_eval_fun(wrapped_fun.call_wrapped,
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/jax/_src/interpreters/partial_eval.py", line 670, in abstract_eval_fun
    _, avals_out, _ = trace_to_jaxpr_dynamic(
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/jax/_src/interpreters/partial_eval.py", line 2155, in trace_to_jaxpr_dynamic
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/jax/_src/interpreters/partial_eval.py", line 2177, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers_)
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/jax/_src/linear_util.py", line 188, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/jax/_src/linear_util.py", line 188, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "diffusers/examples/text_to_image/test_resource_exhausted.py", line 88, in init_fn
    variables = model.init(k, x)  # Initialize the model.
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/flax/linen/module.py", line 1846, in init
    _, v_out = self.init_with_output(
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/flax/linen/module.py", line 1729, in init_with_output
    raise errors.InvalidRngError(
jax._src.traceback_util.UnfilteredStackTrace: flax.errors.InvalidRngError: RNGs should be of shape (2,) or KeyArray in Module MLP, but rngs are: Traced<ShapedArray(key<fry>[])>with<DynamicJaxprTrace(level=1/0)> (https://flax.readthedocs.io/en/latest/api_reference/flax.errors.html#flax.errors.InvalidRngError)

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "diffusers/examples/text_to_image/test_resource_exhausted.py", line 123, in <module>
    main()
  File "diffusers/examples/text_to_image/test_resource_exhausted.py", line 114, in main
    abstract_variables = jax.eval_shape(functools.partial(init_fn, model=model, optimizer=optimizer), k, x)
  File "diffusers/examples/text_to_image/test_resource_exhausted.py", line 88, in init_fn
    variables = model.init(k, x)  # Initialize the model.
flax.errors.InvalidRngError: RNGs should be of shape (2,) or KeyArray in Module MLP, but rngs are: Traced<ShapedArray(key<fry>[])>with<DynamicJaxprTrace(level=1/0)> (https://flax.readthedocs.io/en/latest/api_reference/flax.errors.html#flax.errors.InvalidRngError)
```

### System information

- OS Platform and Distribution: Ubuntu 20.04.4 LTS
- Flax, jax, jaxlib versions (obtain with `pip show flax jax jaxlib`:
```
-> pip show flax jax jaxlib
Name: flax
Version: 0.7.2
Summary: Flax: A neural network library for JAX designed for flexibility
Home-page: 
Author: 
Author-email: Flax team <flax-dev@google.com>
License: 
Location: /home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages
Requires: jax, msgpack, numpy, optax, orbax-checkpoint, PyYAML, rich, tensorstore, typing-extensions
Required-by: 
---
Name: jax
Version: 0.4.13
Summary: Differentiate, compile, and transform Numpy code.
Home-page: https://github.com/google/jax
Author: JAX team
Author-email: jax-dev@google.com
License: Apache-2.0
Location: /home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages
Requires: importlib-metadata, ml-dtypes, numpy, opt-einsum, scipy
Required-by: chex, flax, optax, orbax-checkpoint
---
Name: jaxlib
Version: 0.4.13
Summary: XLA library for JAX
Home-page: https://github.com/google/jax
Author: JAX team
Author-email: jax-dev@google.com
License: Apache-2.0
Location: /home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages
Requires: ml-dtypes, numpy, scipy
Required-by: chex, optax, orbax-checkpoint
```
- Python version: Python 3.8.18
- GPU/TPU model and memory: Google TPU v3-8 
- CUDA version (if applicable): None 

### Problem you have encountered:
Code from this step https://flax.readthedocs.io/en/latest/guides/parallel_training/flax_on_pjit.html#the-output-s-sharding, to be exact, this lines: 

```python

def init_fn(k, x, model, optimizer):
  variables = model.init(k, x) # Initialize the model.
  state = train_state.TrainState.create( # Create a `TrainState`.
    apply_fn=model.apply,
    params=variables['params'],
    tx=optimizer)
  return state

k = random.key(0)
(...)
abstract_variables = jax.eval_shape(functools.partial(init_fn, model=model, optimizer=optimizer), k, x)
```
throws an error 
```
Traceback (most recent call last):
  File "diffusers/examples/text_to_image/test_resource_exhausted.py", line 123, in <module>
    main()
  File "diffusers/examples/text_to_image/test_resource_exhausted.py", line 114, in main
    abstract_variables = jax.eval_shape(functools.partial(init_fn, model=model, optimizer=optimizer), k, x)
  File "diffusers/examples/text_to_image/test_resource_exhausted.py", line 88, in init_fn
    variables = model.init(k, x)  # Initialize the model.
flax.errors.InvalidRngError: RNGs should be of shape (2,) or KeyArray in Module MLP, but rngs are: Traced<ShapedArray(key<fry>[])>with<DynamicJaxprTrace(level=1/0)> (https://flax.readthedocs.io/en/latest/api_reference/flax.errors.html#flax.errors.InvalidRngError)
```

### What you expected to happen:
Guide works as it is

### Steps to reproduce:
Follow guide from https://flax.readthedocs.io/en/latest/guides/parallel_training/flax_on_pjit.html

Full script to the step [The output’s sharding](https://flax.readthedocs.io/en/latest/guides/parallel_training/flax_on_pjit.html#the-output-s-sharding)
```python
import functools
import os
from typing import Any, Callable, Optional

import flax
import jax
import jax.lib.xla_bridge
import jax.numpy as jnp
import jaxlib.xla_client
import jaxlib.xla_extension
import numpy as np
import optax
from flax import linen as nn
from flax import struct, traverse_util
from flax.core import freeze, unfreeze
from flax.training import checkpoints, train_state
from jax import lax, random
from jax import numpy as jnp
from jax.experimental import mesh_utils
from jax.lax import with_sharding_constraint
from jax.sharding import Mesh, NamedSharding, PartitionSpec


print(jax.devices())
device_mesh = mesh_utils.create_device_mesh((2, 4))
print(device_mesh)

mesh = Mesh(devices=device_mesh, axis_names=("data", "model"))
print(mesh)


def mesh_sharding(pspec: PartitionSpec) -> NamedSharding:
    return NamedSharding(mesh, pspec)


class DotReluDot(nn.Module):
    depth: int
    dense_init: Callable = nn.initializers.xavier_normal()

    @nn.compact
    def __call__(self, x):
        y = nn.Dense(
            self.depth,
            kernel_init=nn.with_partitioning(self.dense_init, (None, "model")),
            use_bias=False,  # or overwrite with `bias_init`
        )(x)
        y = jax.nn.relu(y)
        # force a local sharding annotation
        y = with_sharding_constraint(y, mesh_sharding(PartitionSpec("data", "model")))

        W2 = self.param(
            "W2",
            nn.with_partitioning(self.dense_init, ("model", None)),
            (self.depth, x.shape[-1]),
        )

        z = jnp.dot(W2)

        # force a local sharding annotation
        z = with_sharding_constraint(z, mesh_sharding(PartitionSpec("data", None)))

        # return a tuple to confirm
        return z, None


class MLP(nn.Module):
    num_layers: int
    depth: int
    use_scan: bool

    @nn.compact
    def __call__(self, x):
        if self.use_scan:
            x, _ = nn.scan(
                DotReluDot,
                length=self.num_layers,
                variable_axes={"params": 0},
                split_rngs={"params": True},
                metadata_params={nn.PARTITION_NAME: None},
            )(self.depth)(x)
        else:
            for i in range(self.num_layers):
                x, _ = DotReluDot(self.depth)(x)
        return x


def init_fn(k, x, model, optimizer):
    variables = model.init(k, x)  # Initialize the model.
    state = train_state.TrainState.create(  # Create a `TrainState`.
        apply_fn=model.apply, params=variables["params"], tx=optimizer
    )
    return state


def main():
    # MLP hyperparameters.
    BATCH, LAYERS, DEPTH, USE_SCAN = 8, 4, 1024, False

    # Create fake inputs.
    x = jnp.ones((BATCH, DEPTH))
    # Initialize a PRNG key.
    k = random.key(0)

    # Create an Optax optimizer.
    optimizer = optax.adam(learning_rate=0.001)
    # Instantiate the model.
    model = MLP(LAYERS, DEPTH, USE_SCAN)

    x_sharding = mesh_sharding(PartitionSpec("data", None))  # dimensions: (batch, length)
    x = jax.device_put(x, x_sharding)
    jax.debug.visualize_array_sharding(x)

    # Create an abstract closure to wrap the function before feeding it in because `jax.eval_shape` only takes pytrees as arguments.
    abstract_variables = jax.eval_shape(functools.partial(init_fn, model=model, optimizer=optimizer), k, x)

    # This `state_sharding` has the same pytree structure as `state`, the output of the `init_fn`.
    state_sharding = nn.get_sharding(abstract_variables, mesh)
    print(state_sharding)


if __name__ == "__main__":
    main()

``` 

To be sure that is not an package issue i created new conda venv
```
conda create --name tmp python=3.8
conda activate tmp
pip install jax[tpu] -f https://storage.googleapis.com/jax-releases/libtpu_releases.html
pip install -U flax
```
I did not try any other workarounds.

**Comment by PawKanarek** [comment]
If I cannot do hard stuff, I will start with 101:)
The docs about random https://jax.readthedocs.io/en/latest/jax-101/05-random-numbers.html indicates that `PRNGKey(42)` generates array of `shape (2,)` So it looks like the problem is in `random.key(0)` initialization, we should rather use `random.PRNGKey(0)` because error tells us that the `shape (2,)` is expected. 

### The [docs](https://flax.readthedocs.io/en/latest/guides/parallel_training/flax_on_pjit.html) should change that line to fix this problem: 
```python
--- k = random.key(0) 
+++ k = random.PRNGKey(42)
```  

Sadly shortly after, the new error occurred: 
```
  File "diffusers/examples/text_to_image/test_resource_exhausted.py", line 57, in __call__
    z = jnp.dot(W2)
TypeError: dot() missing 1 required positional argument: 'b'
```
<details>
<summary>Full logs</summary>

```
(tmp) raix@t1v-n-d3214137-w-0:/mnt/disks/persist/repos$ python diffusers/examples/text_to_image/test_resource_exhausted.py 
WARNING:absl:Tensorflow library not found, tensorflow.io.gfile operations will use native shim calls. GCS paths (i.e. 'gs://...') cannot be accessed.
[TpuDevice(id=0, process_index=0, coords=(0,0,0), core_on_chip=0), TpuDevice(id=1, process_index=0, coords=(0,0,0), core_on_chip=1), TpuDevice(id=2, process_index=0, coords=(1,0,0), core_on_chip=0), TpuDevice(id=3, process_index=0, coords=(1,0,0), core_on_chip=1), TpuDevice(id=4, process_index=0, coords=(0,1,0), core_on_chip=0), TpuDevice(id=5, process_index=0, coords=(0,1,0), core_on_chip=1), TpuDevice(id=6, process_index=0, coords=(1,1,0), core_on_chip=0), TpuDevice(id=7, process_index=0, coords=(1,1,0), core_on_chip=1)]
[[TpuDevice(id=0, process_index=0, coords=(0,0,0), core_on_chip=0)
  TpuDevice(id=1, process_index=0, coords=(0,0,0), core_on_chip=1)
  TpuDevice(id=2, process_index=0, coords=(1,0,0), core_on_chip=0)
  TpuDevice(id=3, process_index=0, coords=(1,0,0), core_on_chip=1)]
 [TpuDevice(id=6, process_index=0, coords=(1,1,0), core_on_chip=0)
  TpuDevice(id=7, process_index=0, coords=(1,1,0), core_on_chip=1)
  TpuDevice(id=4, process_index=0, coords=(0,1,0), core_on_chip=0)
  TpuDevice(id=5, process_index=0, coords=(0,1,0), core_on_chip=1)]]
Mesh(device_ids=array([[0, 1, 2, 3],
       [6, 7, 4, 5]]), axis_names=('data', 'model'))
                                                                                
                                                                                
                                  TPU 0,1,2,3                                   
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                  TPU 4,5,6,7                                   
                                                                                
                                                                                
                                                                                
Traceback (most recent call last):
  File "diffusers/examples/text_to_image/test_resource_exhausted.py", line 122, in <module>
    main()
  File "diffusers/examples/text_to_image/test_resource_exhausted.py", line 114, in main
    abstract_variables = jax.eval_shape(functools.partial(init_fn, model=model, optimizer=optimizer), k, x)
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/jax/_src/api.py", line 2783, in eval_shape
    out = pe.abstract_eval_fun(wrapped_fun.call_wrapped,
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/jax/_src/interpreters/partial_eval.py", line 670, in abstract_eval_fun
    _, avals_out, _ = trace_to_jaxpr_dynamic(
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/jax/_src/interpreters/partial_eval.py", line 2155, in trace_to_jaxpr_dynamic
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/jax/_src/interpreters/partial_eval.py", line 2177, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers_)
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/jax/_src/linear_util.py", line 188, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/jax/_src/linear_util.py", line 188, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "diffusers/examples/text_to_image/test_resource_exhausted.py", line 88, in init_fn
    variables = model.init(k, x)  # Initialize the model.
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/flax/linen/module.py", line 1846, in init
    _, v_out = self.init_with_output(
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/flax/linen/module.py", line 1747, in init_with_output
    return init_with_output(
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/flax/core/scope.py", line 1034, in wrapper
    return apply(fn, mutable=mutable, flags=init_flags)(
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/flax/core/scope.py", line 998, in wrapper
    y = fn(root, *args, **kwargs)
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/flax/linen/module.py", line 2371, in scope_fn
    return fn(module.clone(parent=scope, _deep_clone=True), *args, **kwargs)
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/flax/linen/module.py", line 467, in wrapped_module_method
    return self._call_wrapped_method(fun, args, kwargs)
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/flax/linen/module.py", line 967, in _call_wrapped_method
    y = fun(self, *args, **kwargs)
  File "diffusers/examples/text_to_image/test_resource_exhausted.py", line 83, in __call__
    x, _ = DotReluDot(self.depth)(x)
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/flax/linen/module.py", line 467, in wrapped_module_method
    return self._call_wrapped_method(fun, args, kwargs)
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/flax/linen/module.py", line 967, in _call_wrapped_method
    y = fun(self, *args, **kwargs)
  File "diffusers/examples/text_to_image/test_resource_exhausted.py", line 57, in __call__
    z = jnp.dot(W2)
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/jax/_src/pjit.py", line 250, in cache_miss
    outs, out_flat, out_tree, args_flat, jaxpr = _python_pjit_helper(
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/jax/_src/pjit.py", line 158, in _python_pjit_helper
    args_flat, _, params, in_tree, out_tree, _ = infer_params_fn(
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/jax/_src/api.py", line 306, in infer_params
    return pjit.common_infer_params(pjit_info_args, *args, **kwargs)
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/jax/_src/pjit.py", line 505, in common_infer_params
    jaxpr, consts, canonicalized_out_shardings_flat = _pjit_jaxpr(
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/jax/_src/pjit.py", line 971, in _pjit_jaxpr
    jaxpr, final_consts, out_type = _create_pjit_jaxpr(
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/jax/_src/linear_util.py", line 345, in memoized_fun
    ans = call(fun, *args)
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/jax/_src/pjit.py", line 924, in _create_pjit_jaxpr
    jaxpr, global_out_avals, consts = pe.trace_to_jaxpr_dynamic(
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/jax/_src/interpreters/partial_eval.py", line 2155, in trace_to_jaxpr_dynamic
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/jax/_src/interpreters/partial_eval.py", line 2177, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers_)
  File "/home/raix/miniconda3/envs/tmp/lib/python3.8/site-packages/jax/_src/linear_util.py", line 188, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
jax._src.traceback_util.UnfilteredStackTrace: TypeError: dot() missing 1 required positional argument: 'b'

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "diffusers/examples/text_to_image/test_resource_exhausted.py", line 122, in <module>
    main()
  File "diffusers/examples/text_to_image/test_resource_exhausted.py", line 114, in main
    abstract_variables = jax.eval_shape(functools.partial(init_fn, model=model, optimizer=optimizer), k, x)
  File "diffusers/examples/text_to_image/test_resource_exhausted.py", line 88, in init_fn
    variables = model.init(k, x)  # Initialize the model.
  File "diffusers/examples/text_to_image/test_resource_exhausted.py", line 83, in __call__
    x, _ = DotReluDot(self.depth)(x)
  File "diffusers/examples/text_to_image/test_resource_exhausted.py", line 57, in __call__
    z = jnp.dot(W2)
TypeError: dot() missing 1 required positional argument: 'b'
```

</details>

**Comment by chiamp** [comment]
Flax supports the new-style RNG keys (i.e. `jax.random.key`) from version `0.7.3` and onward, but it seems like you are using version `0.7.2`. Flax only supports Python versions [`3.9` or higher](https://github.com/google/flax/blob/main/pyproject.toml#L7), so you won't be able to get a higher Flax version than `0.7.2` on Python `3.8`. You could use the old-style RNG keys (i.e. `jax.random. PRNGKey`) like you mentioned, or you can upgrade your Python version.

>   File "diffusers/examples/text_to_image/test_resource_exhausted.py", line 57, in __call__
    z = jnp.dot(W2)
TypeError: dot() missing 1 required positional argument: 'b'

You need to provide a [`b`](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.dot.html) argument to this function.

**Comment by PawKanarek** [comment]
@chiamp Thank you! Looks like everything is solved now!
