### ISSUE TITLE
Some problem about example mnist - AssertionError

### ISSUE THREAD

**Issue by samaritanhu** [google/flax#382]
Provide as much information as possible. At least, this should include a description of your issue and steps to reproduce the problem. If possible also provide a summary of what steps or workarounds you have already tried.

### Problem you have encountered:
Since I don't have GPU/TPU at this MacBook Pro, thus I just run it by CPU. After I tried `python train.py --model_dir=/tmp/mnist`, my python appeared `AssertionError` and I don't know why...

### What you expected to happen:
I wish this would run very smoothly. I have another problem here - because in `examples/mnist/train.py`, it has `from flax import nn`, do I need to use `pip install flax` before this script runs? Otherwise, in my former experience, I would add `from __future__ import absolute_import` since the flax directory wasn't in the mnist directory. 

### Logs, error messages, etc:
Traceback (most recent call last):
  File "train.py", line 211, in <module>
    app.run(main)
  File "/opt/anaconda3/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/opt/anaconda3/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "train.py", line 207, in main
    train(train_ds, test_ds)
  File "train.py", line 187, in train
    model = create_model(init_rng)
  File "train.py", line 82, in create_model
    _, initial_params = CNN.init_by_shape(key, [((1, 28, 28, 1), jnp.float32)])
  File "/opt/anaconda3/lib/python3.7/site-packages/flax/nn/base.py", line 221, in wrapper
    return super_fn(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/flax/nn/base.py", line 512, in init_by_shape
    return jax_utils.partial_eval_by_shape(lazy_init, input_specs)
  File "/opt/anaconda3/lib/python3.7/site-packages/flax/jax_utils.py", line 119, in partial_eval_by_shape
    _, out_pvals, _ = pe.trace_to_jaxpr(f_flat, in_pvals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/interpreters/partial_eval.py", line 423, in trace_to_jaxpr
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/linear_util.py", line 150, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/opt/anaconda3/lib/python3.7/site-packages/flax/jax_utils.py", line 111, in <lambda>
    f = lambda *inputs: fn(*inputs, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/flax/nn/base.py", line 511, in lazy_init
    return init_fn()
  File "/opt/anaconda3/lib/python3.7/site-packages/flax/nn/base.py", line 503, in init_fn
    return cls.init(_rng, *(inputs + args), name=name, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/flax/nn/base.py", line 221, in wrapper
    return super_fn(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/flax/nn/base.py", line 465, in init
    y = instance.apply(*args, **kwargs)
  File "train.py", line 68, in apply
    x = nn.relu(x)
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/custom_derivatives.py", line 233, in __call__
    out_flat = custom_jvp_call(flat_fun, flat_jvp, *args_flat)
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/custom_derivatives.py", line 284, in bind
    outs = top_trace.process_custom_jvp_call(self, fun, jvp, tracers)
  File "/opt/anaconda3/lib/python3.7/site-packages/jax/interpreters/partial_eval.py", line 291, in process_custom_jvp_call
    assert self.master.trace_type is StagingJaxprTrace
AssertionError

### Steps to reproduce:
Whenever possible, please provide a *minimal example*. Please consider submitting it as a Colab link.

**Comment by levskaya** [comment]
@samaritanhu - sorry about that, there's a recent core JAX change that shouldn't have affected us but does in fact seem to, do you want to try adding these lines to the top of your file?
```
from jax.config import config
config.enable_omnistaging()
```

**Comment by levskaya** [comment]
#393 should also fix this.

**Comment by jheek** [comment]
Closing because this was fixed in #393
