### ISSUE TITLE
New python venv fails to pip install the flax mnist example requirements

### ISSUE THREAD

**Issue by sycamoreoak** [google/flax#3990]
New python venv fails to pip install the mnist example requirements

### System information
- OS Platform and Distribution: Linux Ubuntu 22.04.4 LTS
- Flax, jax, jaxlib versions (obtain with `pip show flax jax jaxlib`:
```
(mnenv) ~/src/python/flax/examples/mnist$ pip show flax jax jaxlib
WARNING: Package(s) not found: flax, jax, jaxlib
```
- Python version: Python 3.10.12
- GPU/TPU model and memory: RTX 4070
- CUDA version (if applicable): 
```
 nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Jun_13_19:16:58_PDT_2023
Cuda compilation tools, release 12.2, V12.2.91
Build cuda_12.2.r12.2/compiler.32965470_0
```

### Problem you have encountered:
The pip install requirements fails for the mnist example

```
~/src/python/flax/examples/mnist$ python3 -m venv mnenv
~/src/python/flax/examples/mnist$ source ./mnenv/bin/activate
(mnenv) ~/src/python/flax/examples/mnist$ pip install -r ./requirements.txt Looking in links: https://storage.googleapis.com/jax-releases/jax_releases.html
DEPRECATION: The HTML index page being used (https://storage.googleapis.com/jax-releases/jax_releases.html) is not a proper HTML 5 document. This is in violation of PEP 503 which requires these pages to be well-formed HTML 5 documents. Please reach out to the owners of this index page, and ask them to update this index page to a valid HTML 5 document. pip 22.2 will enforce this behaviour change. Discussion can be found at https://github.com/pypa/pip/issues/10825
Collecting absl-py==1.0.0
  Using cached absl_py-1.0.0-py3-none-any.whl (126 kB)
Collecting clu==0.0.6
  Using cached clu-0.0.6-py3-none-any.whl (77 kB)
Collecting flax==0.4.1
  Using cached flax-0.4.1-py3-none-any.whl (184 kB)
Collecting jax==0.3.4
  Using cached jax-0.3.4.tar.gz (924 kB)
  Preparing metadata (setup.py) ... done
ERROR: Could not find a version that satisfies the requirement jaxlib==0.3.2+cuda11.cudnn82 (from versions: 0.1.75, 0.1.76, 0.3.0, 0.3.2, 0.3.5, 0.3.7, 0.3.8, 0.3.10, 0.3.14, 0.3.15, 0.3.18, 0.3.20, 0.3.22, 0.3.24, 0.3.25, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.6, 0.4.7, 0.4.9, 0.4.10, 0.4.11, 0.4.12, 0.4.13, 0.4.14, 0.4.16, 0.4.17, 0.4.18, 0.4.19, 0.4.20, 0.4.21, 0.4.22, 0.4.23, 0.4.24, 0.4.25, 0.4.26, 0.4.27, 0.4.28, 0.4.29)
ERROR: No matching distribution found for jaxlib==0.3.2+cuda11.cudnn82
```

### What you expected to happen:
mnist, make it so.

### Logs, error messages, etc:
```
ERROR: Could not find a version that satisfies the requirement jaxlib==0.3.2+cuda11.cudnn82 (from versions: 0.1.75, 0.1.76, 0.3.0, 0.3.2, 0.3.5, 0.3.7, 0.3.8, 0.3.10, 0.3.14, 0.3.15, 0.3.18, 0.3.20, 0.3.22, 0.3.24, 0.3.25, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.6, 0.4.7, 0.4.9, 0.4.10, 0.4.11, 0.4.12, 0.4.13, 0.4.14, 0.4.16, 0.4.17, 0.4.18, 0.4.19, 0.4.20, 0.4.21, 0.4.22, 0.4.23, 0.4.24, 0.4.25, 0.4.26, 0.4.27, 0.4.28, 0.4.29)
```

### Steps to reproduce:
Seems like a fresh venv on an up-to-date stable ubuntu with an nvidia GPU should reproduce this...

**Comment by pascal-mueller** [comment]
Also unable to use flax at all (tested on 3.8, 3.11, 3.12):

```py
% python
Python 3.11.6 (main, Oct  2 2023, 22:00:51) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
> import flax.linen
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File ".../project_3/flax.py", line 6, in <module>
>     import flax.linen as nn
> ModuleNotFoundError: No module named 'flax.linen'; 'flax' is not a package
```

I'm on an M1 machine if that somehow matters.
