### ISSUE TITLE
pytype breaks on macOS

### ISSUE THREAD

**Issue by VIVelev** [google/flax#725]
The following issue relates only to the **development** of *Flax*, not the usage. In essence, it is a *pytype* issue ([Pytype fails on MacOSX(Mojave-10.14.9) when inferring types.](https://github.com/google/pytype/issues/661)), but it negatively impacts the development of *Flax* on macOS.

### Problem you have encountered:

Upon following the instructions from [contributing.md](https://github.com/google/flax/blob/master/contributing.md), `./tests/run_all_tests.sh` breaks.

  - more specifically: `pytype flax/`
    - even more:
```
pytype-single --imports_info .pytype/imports/flax.core.scope.imports --module-name flax.core.scope -V 3.8 -o .pytype/pyi/flax/core/scope.pyi --analyze-annotated --nofail --quick flax/core/scope.py
```

### Stack trace:
```
ERROR:pytype.imports_map_loader Invalid imports_map entries (checking from root dir: /Users/vivelev/Desktop/flax)
ERROR:pytype.imports_map_loader   file does not exist: '/Users/vivelev/Desktop/flax/.pytype/pyi/flax/core/scope.pyi' (mapped from 'flax/core/scope')
Traceback (most recent call last):
  File "/Users/vivelev/Desktop/flax/.env/bin/pytype-single", line 8, in <module>
    sys.exit(main())
  File "/Users/vivelev/Desktop/flax/.env/lib/python3.8/site-packages/pytype/single.py", line 63, in main
    options = config.Options(sys.argv[1:], command_line=True)
  File "/Users/vivelev/Desktop/flax/.env/lib/python3.8/site-packages/pytype/config.py", line 68, in __init__
    Postprocessor(names, options, self).process()
  File "/Users/vivelev/Desktop/flax/.env/lib/python3.8/site-packages/pytype/config.py", line 406, in process
    node.processor(value)
  File "/Users/vivelev/Desktop/flax/.env/lib/python3.8/site-packages/pytype/config.py", line 541, in _store_imports_map
    self.output_options.imports_map = imports_map_loader.build_imports_map(
  File "/Users/vivelev/Desktop/flax/.env/lib/python3.8/site-packages/pytype/imports_map_loader.py", line 91, in build_imports_map
    raise ValueError(msg)
ValueError: Invalid imports_map: .pytype/imports/flax.core.scope.imports
Bad entries:
  flax/core/scope -> /Users/vivelev/Desktop/flax/.pytype/pyi/flax/core/scope.pyi
```

### Steps to reproduce:

Information about my system:
  - OS: macOS 11.0.1 (Although, judging by the *pytype* isssue linked above, it will probably break on older versions too.)
  - Python: v3.8.6 (also tried on v3.6.12 and v3.7.9)

Steps: [contributing.md](https://github.com/google/flax/blob/master/contributing.md)

### A hacky solution:
The problem seems to stem from the fact that in several places in the *Flax* source code the `Scope` class is imported as:
```
from flax.core import Scope
```
rather then:
```
from flax.core.scope import Scope
```

As a result, for reasons unknown to me, *pytype* on macOS thinks there is a file `flax/core/Scope.py`, searches for it, and fails.

Sadly, however, simply replacing all `from flax.core import Scope` with `from flax.core.scope import Scope` doesn't work: it fixes the *Flax* error, but for some reason it fails to process the *JAX* API accurately, raising the new error `No attribute 'xla' on module 'jax.interpreters'`.

**The only solution I found so far is as follows:**
1) Replace `from flax.core import Scope` with `from flax.core.scope import Scope` in the following files:
  - flax/core/nn/attention.py
  - flax/core/nn/linear.py
  - flax/core/nn/normalization.py
2) First run `pytype flax/core/scope.py` and then `pytype flax/`

(If you want, I can open a PR with the fixes. Although, imo they are really brittle.)

### A proposal:

I see you want to run both *mypy* and *pytype* in `run_all_tests.sh`  (#688), but why not only *mypy*? From my experience, *mypy* is better supported for OSs other than Linux. Is there a specific benefit you seek from using *pytype*? The inference? Not being as strict as *mypy*?

I would be more than glad to help you transition from *pytype* to *mypy*. :)

**Comment by jheek** [comment]
We were not aware of the cross-platform issues with PyType before.
We will probably switch to using mypy in run_all_tests by default if it turns out pytype is too brittle.

**Comment by VIVelev** [comment]
@jheek @avital Can I try myself in incorporating *mypy* into the workflow and making *pytype* optional? Or is it a task to be done by the Core Team?

**Comment by jheek** [comment]
A PR is very much welcome actually! Here is the "PR welcome" issuet tracking this: https://github.com/google/flax/issues/688

**Comment by avital** [comment]
@VIVelev do you want to give a shot at making pytype optional and getting mypy running on Flax? We are discussing with the pytype team in Google as to why it passes internally but fails externally, but probably using mypy in OSS is a better idea anyways. If you want to give it a shot, feel free to do so! Nobody on Flax Core is currently looking at mypy.

Is it better to keep the conversation about mypy only on #688? Then we can use this issue to track any improvements we learn about PyType, but I wouldn't recommend restructuring our code around OSS pytype at the moment, as seems like mypy is the de facto standard.

**Comment by VIVelev** [comment]
@avital Yeah, gladly. I am currently working on it in my spare time. But, isn't using both mypy and pytype a bit redundant? I mean, if Flax passes mypy, shouldn't it also pass pytype, at least at a sufficient level.

I agree with the issue coordination.

**Comment by avital** [comment]
pytype and mypy differ in various fine details, but we need pytype to pass for the internal Google build system. Looks like Google-internal pytype and open source pytype also differ in some ways, though.

**Comment by levskaya** [comment]
With `py3.9` and `pytype==2022.8.3` pytype no longer seems to be failing on MacOS 12.15, so I'll close this issue for now.
